Repository stellaGK/stella, pull requests merged in 2024-07, with the labels that each got.

#132 Fix integrated tests and compilation tests
  Makefile
  geo/vmec_interface/CMakeLists.txt
  scripts/ci_cmake_build_and_run.sh
  tests/integrated/Makefile
  tests/integrated/requirements.txt
Labels: bugfix

#135 Merge Full Flux Surface code into Master with Electromagnetic effects
  CMakeLists.txt
  Makefile.depend
  dissipation/hyper.f90
  ffs_solve.f90
  fields.fpp
  finite_differences.f90
  g_tofrom_h.f90
  geo/millerlocal.f90
  geo/stella_geometry.f90
  geo/vmec_geo.f90
  geo/vmec_interface/vmec_to_stella_geometry_interface.f90
  gyro_averages.f90
  implicit_solve.f90
  init_g.f90
  kt_grids.f90
  mirror_terms.f90
  parallel_streaming.f90
  physics_parameters.f90
  response_matrix.fpp
  run_parameters.f90
  stella_diagnostics.f90
  tests/automated_numerical_tests_for_stella/test_4_fluxtube/test_useless_flags1.in
  time_advance.f90
  volume_averages.f90
  vpamu_grids.f90
Labels: enhancement, stella review 07/2024

#114 Added a makefile for NERSC perlmutter
  Makefiles/Makefile.perlmutter
Labels: small feature
